"""Add timestamp column to Resource table

Revision ID: 84c52ec1d9d8
Revises: 995ca21480a3
Create Date: 2025-05-21 11:41:16.389949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c52ec1d9d8'
down_revision = '995ca21480a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_resource_resource_type')
        batch_op.create_index(batch_op.f('ix_resource_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_resource_timestamp'))
        batch_op.create_index('ix_resource_resource_type', ['resource_type'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
